#!/usr/bin/env bash

# Set up autograder files
pattern="/autograder/submission/*.py"
files=( $pattern )
cp "${files[0]}" /autograder/source/relay.py
cd /autograder/source
python3 run_tests.py

#vim: ft=sh
